services:
  frontend:
    build: ./src/front-end
    ports:
      - "443"
    depends_on:
      - backend
    volumes:
      - ./src/front-end:/app
      - /app/node_modules
      - ./src/back-end/vault_handler/secrets/ssl_certs/transssl.crt:/etc/nginx/ssl/transssl.crt:ro
      - ./src/back-end/vault_handler/secrets/ssl_certs/transssl.key:/etc/nginx/ssl/transssl.key:ro
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=production
    networks:
      - ft_transcendence_net
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:5000"
        # syslog-address: "udp://127.0.0.1:5000" #mac os workaround
        tag: "frontend"
        syslog-format: "rfc5424"
    labels:
      service.name: "frontend"
      service.type: "web"
      app.component: "ui"



  backend:
    build:
      context: ./src/back-end
      dockerfile: Dockerfile
    ports:
      - "3010"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VAULT_ADDR=https://vault:8200
    networks:
      - ft_transcendence_net
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:5000"
        #syslog-address: "udp://127.0.0.1:5000" #mac os workaround
        tag: "backend"
        syslog-format: "rfc5424"
    labels:
      service.name: "backend"
      service.type: "api"
      app.component: "server"
    volumes:
      - ./src/back-end/vault_handler/secrets/vault_certs/vault.crt:/app/vault_certs/vault.crt:ro
      - ./src/back-end/vault_handler/secrets/ssl_certs:/app/ssl_certs:ro
      - ./src/back-end/vault_handler/secrets:/app/vault_handler/secrets:rw
      - ./src/back-end/database_sql.db:/app/database_sql.db:rw
      - ./src/back-end/uploads:/app/uploads:rw
    entrypoint: ["node", "server.js"]
    depends_on:
      - vault

  modsec-proxy:
    image: owasp/modsecurity-crs:3.3.7-nginx-alpine-202510030310
    container_name: modsecurity
    ports:
      - "5173:443"
    environment:
      - PARANOIA=1
      - ANOMALY_INBOUND=10
      - ANOMALY_OUTBOUND=5
      - BLOCKING_PARANOIA=2
      - LOGLEVEL=debug
    volumes:
      - ./src/modsecurity/nginx-custom.conf:/etc/nginx/conf.d/reverse-proxy.conf:ro
      - ./src/back-end/vault_handler/secrets/ssl_certs/transssl.crt:/etc/nginx/ssl/transssl.crt:ro
      - ./src/back-end/vault_handler/secrets/ssl_certs/transssl.key:/etc/nginx/ssl/transssl.key:ro
    depends_on:
      - frontend
    networks:
      - ft_transcendence_net

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK                             # prevent memory swap for secrets
    environment:
      - VAULT_ADDR=https://0.0.0.0:8200
    volumes:
      - ./vault/vault-data:/vault/file             # persistent data
      - ./vault/vault-config:/vault/config         # mount config and certs
      - ./src/back-end/vault_handler/secrets/vault_certs:/vault/config/certs:ro
    entrypoint: ["vault", "server", "-config=/vault/config/vault.hcl"]
    networks:
      - ft_transcendence_net

volumes:
  sqlite-data:

networks:
  ft_transcendence_net:
    external: true
    driver: bridge
