server {
    listen 443 ssl;
    server_name localhost;

	client_max_body_size 5M;
    root /usr/share/nginx/html;
    index index.html;

    ssl_certificate     /etc/nginx/ssl/transssl.crt;
    ssl_certificate_key /etc/nginx/ssl/transssl.key;

    ssl_protocols       TLSv1.2 TLSv1.3;
    # ssl_ciphers         HIGH:!aNULL:!MD5;

    # Serve static files directly
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optional: improve caching for assets (adjust as needed)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?|ttf|eot|otf)$ {
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }

    # Optional: disable .htaccess and hidden files serving
    location ~ /\.(?!well-known).* {
        deny all;
    }
}


# try_files $uri $uri/ /index.html;
#Makes sure all requests that don’t match a file fallback to index.html — critical for SPA routing to work.
#root /usr/share/nginx/html;
#This matches where you copy your built Vite app in your Dockerfile.
#Cache rules are optional but improve performance.
#
#
#
#
#
#
#
